<?php
/**
 * Internationalisation file for EasyTimeline extension.
 *
 * @file
 * @ingroup Extensions
 */

$messages = array();

/** English */
$messages['en'] = array(
	'timeline-desc' => 'Adds <code>&lt;timeline&gt;</code> tag to create timelines',
	'timeline-invalidmap' => 'Invalid image map generated by EasyTimeline',
);

/** Message documentation (Message documentation)
 * @author Raimond Spekking
 * @author Raymond
 * @author Shirayuki
 */
$messages['qqq'] = array(
	'timeline-desc' => 'Extension description displayed on [[Special:Version]]',
	'timeline-invalidmap' => 'Used as error message if failed to load XML or the first node in XML is not "map".',
);

/** Afrikaans (Afrikaans)
 * @author Naudefj
 * @author පසිඳු කාවින්ද
 */
$messages['af'] = array(
	'timeline-desc' => 'Maak die <code>&lt;timeline&gt;</code> etiket beskikbaar om tydslyne te maak',
	'timeline-invalidmap' => 'Ongeldige beeld kaart gegenereer deur EasyTimeline',
);

/** Aragonese (aragonés)
 * @author Juanpabl
 */
$messages['an'] = array(
	'timeline-desc' => "Adibe a etiqueta <code>&lt;timeline&gt;</code> ta creyar linias d'o tiempo",
	'timeline-invalidmap' => "Mapa d'imachen invalida chenerada por EasyTimeline",
);

/** Arabic (العربية)
 * @author Meno25
 */
$messages['ar'] = array(
	'timeline-desc' => 'يضيف الوسم <code>&lt;timeline&gt;</code> لإنشاء الخطوط الزمنية',
	'timeline-invalidmap' => 'صورة خريطة غير صحيحة تم توليدها بواسطة EasyTimeline',
);

/** Egyptian Spoken Arabic (مصرى)
 * @author Ramsis II
 */
$messages['arz'] = array(
	'timeline-desc' => 'بيضيف تاج ال <code>&lt;timeline&gt;</code> علشان ينشيء خطوط الزمن',
);

/** Assamese (অসমীয়া)
 * @author Bishnu Saikia
 * @author Gitartha.bordoloi
 */
$messages['as'] = array(
	'timeline-desc' => 'সময়সীমা সৃষ্টি কৰিবলৈ <code>&lt;timeline&gt;</code> টেগ্‌ যোগ দিয়ে',
	'timeline-invalidmap' => 'সহজ সময়সীমাৰ দ্বাৰা সৃষ্ট অবৈধ ইমেজ মেপ',
);

/** Asturian (asturianu)
 * @author Esbardu
 * @author Xuacu
 */
$messages['ast'] = array(
	'timeline-desc' => 'Añade la etiqueta <code>&lt;timeline&gt;</code> pa crear llinies de tiempu',
	'timeline-invalidmap' => "Mapa d'imaxe inválidu xeneráu por EasyTimeline",
);

/** Azerbaijani (azərbaycanca)
 * @author Khan27
 */
$messages['az'] = array(
	'timeline-desc' => 'Zaman xətti yaratmaq üçün <code>&lt;timeline&gt;</code> etiketini edir',
	'timeline-invalidmap' => 'EasyTimeline tərəfindən etibarsız şəkil xəritəsi yaradıldı',
);

/** Bashkir (башҡортса)
 * @author Assele
 */
$messages['ba'] = array(
	'timeline-desc' => 'Ваҡыт һыҙыҡтарын булдырыу өсөн <code>&lt;timeline&gt;</code> билдәһен өҫтәй',
	'timeline-invalidmap' => 'EasyTimeline тарафынан булдырылған рәсем картаһы дөрөҫ түгел',
);

/** Southern Balochi (بلوچی مکرانی)
 * @author Mostafadaneshvar
 */
$messages['bcc'] = array(
	'timeline-desc' => 'هورکنت <code>&lt;timeline&gt;</code>برچسپء په شرکتن خط زمان',
);

/** Belarusian (Taraškievica orthography) (беларуская (тарашкевіца)‎)
 * @author Jim-by
 */
$messages['be-tarask'] = array(
	'timeline-desc' => 'Дадае тэг <code>&lt;timeline&gt;</code> для стварэньня часавых шкалаў',
	'timeline-invalidmap' => 'Няслушная выява мапы створаная праз EasyTimeline',
);

/** Bulgarian (български)
 * @author DCLXVI
 */
$messages['bg'] = array(
	'timeline-desc' => 'Добавя етикета <code>&lt;timeline&gt;</code> за създаване на времеви линии',
);

/** Bengali (বাংলা)
 * @author Abdullah Harun Jewel
 * @author Nasir8891
 */
$messages['bn'] = array(
	'timeline-desc' => 'সময়সীমা নির্ধারণ
সময়সীমা নির্ধারণ ট্যাগ ব্যবহার করতে যুক্ত করুন: <code>&lt;timeline&gt;</code>',
	'timeline-invalidmap' => 'EasyTimeline ভুল ছবি মানচিত্র তৈরী করেছে',
);

/** Breton (brezhoneg)
 * @author Fulup
 */
$messages['br'] = array(
	'timeline-desc' => 'Ouzhpennañ a ra ar valizenn <code>&lt;timeline&gt;</code> da grouiñ frizennoù kronologel',
	'timeline-invalidmap' => 'Kartenn direizh ganet dre EasyTimeline',
);

/** Bosnian (bosanski)
 * @author CERminator
 */
$messages['bs'] = array(
	'timeline-desc' => 'Dodaje oznaku <code>&lt;timeline&gt;</code> za pravljenje vremenskih linija',
	'timeline-invalidmap' => 'Nevaljana mapa slika generisana putem EasyTimeline',
);

/** Catalan (català)
 * @author El libre
 * @author Paucabot
 */
$messages['ca'] = array(
	'timeline-desc' => "Afegeix l'etiqueta <code>&lt;timeline&gt;</code> per crear cronologies",
	'timeline-invalidmap' => "Mapa d'imatge invàlid generat per EasyTimeline",
);

/** Czech (česky)
 * @author Li-sung
 * @author Mormegil
 */
$messages['cs'] = array(
	'timeline-desc' => 'Přidává značku <code>&lt;timeline&gt;</code> na vytváření časových os',
	'timeline-invalidmap' => 'Neplatná mapa k obrázku vytvořená pomocí EasyTimeline',
);

/** Danish (dansk)
 * @author Christian List
 * @author Peter Alberti
 */
$messages['da'] = array(
	'timeline-desc' => 'Tilføjer tagget <code>&lt;timeline&gt;</code> til at oprette tidslinjer',
	'timeline-invalidmap' => 'Ugyldigt klikbart grafikobjekt genereret af EasyTimeline',
);

/** German (Deutsch)
 * @author Kghbln
 * @author Raimond Spekking
 * @author Umherirrender
 */
$messages['de'] = array(
	'timeline-desc' => 'Ergänzt das Tag <code>&lt;timeline&gt;</code> zur Erstellung von Zeitleisten',
	'timeline-invalidmap' => 'EasyTimeline hat eine ungültige Grafik generiert',
);

/** Zazaki (Zazaki)
 * @author Aspar
 */
$messages['diq'] = array(
	'timeline-desc' => 'qey vıraştışê teqwimi na <code>&lt;timeline&gt;</code> etiket têare keno.',
	'timeline-invalidmap' => 'hetê easyTimeline ra yew xeritaya resmi ya  nemeqbul vıraziya.',
);

/** Lower Sorbian (dolnoserbski)
 * @author Michawiki
 */
$messages['dsb'] = array(
	'timeline-desc' => 'Pśidawa toflicku <code>&lt;timeline&gt;</code> za napóranje casoweje bałki',
	'timeline-invalidmap' => 'Njepłaśiwa wobrazowa kórta napórana pśez EasyTimeline',
);

/** Greek (Ελληνικά)
 * @author Dead3y3
 * @author Omnipaedista
 */
$messages['el'] = array(
	'timeline-desc' => 'Προσθέτει την ετικέτα <code>&lt;timeline&gt;</code> για την δημιουργία χρονολογιών',
	'timeline-invalidmap' => 'Μή έγκυρος χάρτης εικόνας παρηγμένης από το EasyTimeline',
);

/** Esperanto (Esperanto)
 * @author Yekrats
 */
$messages['eo'] = array(
	'timeline-desc' => 'Aldonas etikedon <code>&lt;timeline&gt;</code> por krei tempoaksojn',
	'timeline-invalidmap' => 'Malvalida bildomapo generita de EasyTimeline',
);

/** Spanish (español)
 * @author Crazymadlover
 * @author Remember the dot
 */
$messages['es'] = array(
	'timeline-desc' => 'Añade elemento <code>&lt;timeline&gt;</code> para mostrar cronogramas',
	'timeline-invalidmap' => 'Mapa de imagen inválida generada por EasyTimeline',
);

/** Estonian (eesti)
 * @author Pikne
 */
$messages['et'] = array(
	'timeline-desc' => 'Lisab <code>&lt;timeline&gt;</code>-sildi ajatelgede loomiseks.',
	'timeline-invalidmap' => 'EasyTimeline genereeris vigase kujutise',
);

/** Basque (euskara)
 * @author An13sa
 * @author Theklan
 */
$messages['eu'] = array(
	'timeline-desc' => '<code>&lt;timeline&gt;</code> etiketa gehitzeko du denbora-lerroak sortzeko',
	'timeline-invalidmap' => 'EasyTimeline-k sortutako mapa irudi okerra',
);

/** Persian (فارسی)
 * @author Huji
 * @author Wayiran
 */
$messages['fa'] = array(
	'timeline-desc' => 'برچسب <code>&lt;timeline&gt;</code> را برای نمایش خطوط زمانی می‌افزاید',
	'timeline-invalidmap' => 'تصویر نقشهٔ نامعتبر ایجادشده توسط EasyTimeline',
);

/** Finnish (suomi)
 * @author Crt
 * @author ZeiP
 */
$messages['fi'] = array(
	'timeline-desc' => 'Lisää <code>&lt;timeline&gt;</code>-elementin aikajanan luomiseksi.',
	'timeline-invalidmap' => 'EasyTimeline loi virheellisen kuvakartan',
);

/** French (français)
 * @author Crochet.david
 * @author Grondin
 * @author Urhixidur
 */
$messages['fr'] = array(
	'timeline-desc' => 'Ajoute la balise <code>&lt;timeline&gt;</code> pour créer des frises chronologiques',
	'timeline-invalidmap' => 'Carte de l’image générée par EasyTimeline invalide',
);

/** Franco-Provençal (arpetan)
 * @author ChrisPtDe
 */
$messages['frp'] = array(
	'timeline-desc' => 'Apond la balisa <code>&lt;timeline&gt;</code> por fâre des diagramos cronologicos.',
	'timeline-invalidmap' => 'Mapa envalida de l’émâge fêta per EasyTimeline',
);

/** Friulian (furlan)
 * @author Klenje
 */
$messages['fur'] = array(
	'timeline-desc' => 'Zonte il tag <code>&lt;timeline&gt;</code> par creâ grafics temporâi',
);

/** Galician (galego)
 * @author Toliño
 */
$messages['gl'] = array(
	'timeline-desc' => 'Engade a etiqueta <code>&lt;timeline&gt;</code> para crear liñas do tempo',
	'timeline-invalidmap' => 'Mapa inválido da imaxe xerada por EasyTimeline',
);

/** Ancient Greek (Ἀρχαία ἑλληνικὴ)
 * @author Omnipaedista
 */
$messages['grc'] = array(
	'timeline-desc' => 'Προσθέτει τὴν πινακίδα <timeline> καὶ οὕτως ποιεῖ χρονολογίας',
);

/** Swiss German (Alemannisch)
 * @author Als-Holder
 */
$messages['gsw'] = array(
	'timeline-desc' => 'Fiegt s <code>&lt;timeline&gt;</code>-Tag fir s Aalege vu Zytleischte yy',
	'timeline-invalidmap' => 'EasyTimeline het e nit giltigi Abbildig generiert',
);

/** Gujarati (ગુજરાતી)
 * @author Sushant savla
 */
$messages['gu'] = array(
	'timeline-desc' => 'સમય સારિણી બનાવવા માટે <code>&lt;timeline&gt;</code> ઉમેરે છે',
	'timeline-invalidmap' => 'સરળ સમયરેખા દ્વારા રચાયેલ અવિધ ચિત્ર નક્શો',
);

/** Hebrew (עברית)
 * @author Amire80
 * @author Rotem Liss
 */
$messages['he'] = array(
	'timeline-desc' => 'הוספת תג <code>&lt;timeline&gt;</code> ליצירת צירי זמן',
	'timeline-invalidmap' => 'נוצרה מפת תמונה בלתי תקינה על ידי EasyTimeline',
);

/** Hindi (हिन्दी)
 * @author Ansumang
 * @author Kaustubh
 */
$messages['hi'] = array(
	'timeline-desc' => 'टाईमलाईन तैयार करने के लिये <code>&lt;timeline&gt;</code> टैग देता हैं',
	'timeline-invalidmap' => 'अमान्य छबि नक्शा ईज़ी टाइमलाइन द्वारा बनाया गया है',
);

/** Hiligaynon (Ilonggo)
 * @author Tagimata
 */
$messages['hil'] = array(
	'timeline-desc' => 'Nagadugang <code>&lt;timeline&gt;</code> tag para mahimo ang mga timeline',
);

/** Croatian (hrvatski)
 * @author Dalibor Bosits
 * @author Mnalis
 */
$messages['hr'] = array(
	'timeline-desc' => 'Dodaje <code>&lt;timeline&gt;</code> oznaku za stvaranje vremenskih linija',
	'timeline-invalidmap' => 'EasyTimeline je generirao neispravnu slikovnu mapu',
);

/** Upper Sorbian (hornjoserbsce)
 * @author Michawiki
 */
$messages['hsb'] = array(
	'timeline-desc' => 'Přidawa tafličku <code>&lt;timeline&gt;</code> za wutworjenje časowych lajstow',
	'timeline-invalidmap' => 'Njepłaćiwa wobrazowa karta spłodźena přez EasyTimeline',
);

/** Hungarian (magyar)
 * @author Dani
 * @author Glanthor Reviol
 */
$messages['hu'] = array(
	'timeline-desc' => 'Idővonal készítése a <code>&lt;timeline&gt;</code> tag segítségével',
	'timeline-invalidmap' => 'Az EasyTimeline érvénytelen image mapet generált',
);

/** Interlingua (interlingua)
 * @author McDutchie
 */
$messages['ia'] = array(
	'timeline-desc' => 'Adde le etiquetta <code>&lt;timeline&gt;</code> pro crear lineas temporal',
	'timeline-invalidmap' => 'Mappa de imagine invalide generate per EasyTimeline',
);

/** Indonesian (Bahasa Indonesia)
 * @author Bennylin
 * @author IvanLanin
 */
$messages['id'] = array(
	'timeline-desc' => 'Menambahkan tag <code>&lt;timeline&gt;</code> untuk membuat garis waktu',
	'timeline-invalidmap' => 'Peta gambar tidak sah dibuat oleh EasyTimeline',
);

/** Interlingue (Interlingue)
 * @author Renan
 */
$messages['ie'] = array(
	'timeline-desc' => 'Adjunter puntale <code><timeline></code> por crear lineas de témpor',
	'timeline-invalidmap' => 'Carte geografic de figura ínvalid productet per EasyTimeline',
);

/** Iloko (Ilokano)
 * @author Lam-ang
 */
$messages['ilo'] = array(
	'timeline-desc' => 'Agnayon ti <code>&lt;timeline&gt;</code> nga etiketa tapno agaramid kadagiti panawen pagsurotan',
	'timeline-invalidmap' => 'Imbalido nga imahen ti mapa a napataud ti EasyTimeline',
);

/** Icelandic (íslenska)
 * @author Snævar
 */
$messages['is'] = array(
	'timeline-desc' => 'Bætir við <code>&lt;timeline&gt;</code> tagi til að búa til tímalínur',
	'timeline-invalidmap' => 'Ógild tímalína búin til af EasyTimeline',
);

/** Italian (italiano)
 * @author Beta16
 * @author BrokenArrow
 */
$messages['it'] = array(
	'timeline-desc' => 'Aggiunge il tag <code>&lt;timeline&gt;</code> per creare grafici temporali',
	'timeline-invalidmap' => 'Mappa immagine invalida generata da EasyTimeline',
);

/** Japanese (日本語)
 * @author Fryed-peach
 * @author JtFuruhata
 * @author Shirayuki
 */
$messages['ja'] = array(
	'timeline-desc' => '年表を作成するための <code>&lt;timeline&gt;</code> タグを追加する',
	'timeline-invalidmap' => 'EasyTimeline が生成した無効なイメージマップ',
);

/** Jutish (jysk)
 * @author Huslåke
 */
$messages['jut'] = array(
	'timeline-desc' => 'Tilføje <code>&lt;timeline&gt;</code> tag til kreåsje der tiidlejner',
);

/** Javanese (Basa Jawa)
 * @author Meursault2004
 * @author NoiX180
 */
$messages['jv'] = array(
	'timeline-desc' => 'Nambahaké tag <code>&lt;timeline&gt;</code> kanggo nggawé garis wektu',
	'timeline-invalidmap' => 'Péta gambar ora sah gawéané EasyTimeline',
);

/** Georgian (ქართული)
 * @author Dawid Deutschland
 * @author გიორგიმელა
 */
$messages['ka'] = array(
	'timeline-desc' => 'ჩაამატეთ თეგი <code>&lt;timeline&gt;</code> დროის სკალის შესაქმნელად',
	'timeline-invalidmap' => 'EasyTimeline-მა არასწორი გრაფიკა გამოიმუშავა',
);

/** Khmer (ភាសាខ្មែរ)
 * @author Lovekhmer
 */
$messages['km'] = array(
	'timeline-desc' => 'ដាក់ប្លាក<code>&lt;timeline&gt;</code>ដើម្បីបង្កើតតារាងពេលវេលា',
);

/** Korean (한국어)
 * @author Kwj2772
 * @author ToePeu
 */
$messages['ko'] = array(
	'timeline-desc' => '시간표를 만들기 위해 <code>&lt;timeline&gt;</code> 태그를 추가합니다.',
	'timeline-invalidmap' => 'EasyTimeline이 잘못된 이미지 맵을 생성하였습니다.',
);

/** Colognian (Ripoarisch)
 * @author Purodha
 */
$messages['ksh'] = array(
	'timeline-desc' => 'Deit dä <code>&lt;timeline&gt;</code>-Befäähl em Wiki dobei, wo mer Belldsche med Linnije med ennem Verlauf fun de Zick met maache kann.',
	'timeline-invalidmap' => '<i lang="en">EasyTimeline</i> hädd_e kapot Diajramm afjelivvert',
);

/** Luxembourgish (Lëtzebuergesch)
 * @author Robby
 */
$messages['lb'] = array(
	'timeline-desc' => 'Setzt den <code>&lt;timeline&gt;</code> Tag derbäi fir Zäitlinnen ze maachen',
	'timeline-invalidmap' => 'EasyTimeLine huet e Bild vun enger Kaart generéiert dat net valabel ass',
);

/** Limburgish (Limburgs)
 * @author Matthias
 * @author Ooswesthoesbes
 */
$messages['li'] = array(
	'timeline-desc' => 'Voegt de tag <code>&lt;timeline&gt;</code> toe om tiedliene te make',
	'timeline-invalidmap' => 'Óngeljig gegenereerd EasyTimelineaafbeilding',
);

/** Lithuanian (lietuvių)
 * @author Garas
 * @author Vpovilaitis
 */
$messages['lt'] = array(
	'timeline-desc' => 'Sukuria laiko grafikus naudojant gairę <code>&lt;timeline&gt;</code>',
);

/** Latvian (latviešu)
 * @author Xil
 */
$messages['lv'] = array(
	'timeline-desc' => 'Pievieno <code>&lt;timeline&gt;</code> tagu, lai varētu izveidot hronoloģijas',
	'timeline-invalidmap' => 'EasyTimeline',
);

/** Macedonian (македонски)
 * @author Bjankuloski06
 */
$messages['mk'] = array(
	'timeline-desc' => 'Додава ознака <code>&lt;timeline&gt;</code> за да прави хронологии',
	'timeline-invalidmap' => 'Грешна карта за слика доздадена од EasyTimeline',
);

/** Malayalam (മലയാളം)
 * @author Praveenp
 * @author Shijualex
 */
$messages['ml'] = array(
	'timeline-desc' => 'നാൾ വഴി ഉണ്ടാക്കുവാൻ വേണ്ടി <code>&lt;timeline&gt;</code> എന്ന ടാഗ് ചേർക്കുന്നു',
	'timeline-invalidmap' => 'ഈസിറ്റൈംലൈൻ സൃഷ്ടിച്ച അസാധുവായ രേഖാചിത്രം',
);

/** Marathi (मराठी)
 * @author Kaustubh
 */
$messages['mr'] = array(
	'timeline-desc' => 'टाईमलाईन तयार करण्यासाठी <code>&lt;timeline&gt;</code> टॅग वाढवितो',
);

/** Malay (Bahasa Melayu)
 * @author Aviator
 */
$messages['ms'] = array(
	'timeline-desc' => 'Menambah tag <code>&lt;timeline&gt;</code> untuk mencipta garis masa',
	'timeline-invalidmap' => 'Peta imej yang dijana oleh EasyTimeline tidak sah',
);

/** Norwegian Bokmål (norsk (bokmål)‎)
 */
$messages['nb'] = array(
	'timeline-desc' => 'Legger til taggen <code>&lt;timeline&gt;</code> for å opprette tidslinjer',
	'timeline-invalidmap' => 'Ugyldig bildekart opprettet av EasyTimeline',
);

/** Low German (Plattdüütsch)
 * @author Slomox
 */
$messages['nds'] = array(
	'timeline-desc' => 'Föögt dat <code>&lt;timeline&gt;</code>-Tag för dat Opstellen vun Tietliesten to',
);

/** Dutch (Nederlands)
 * @author Siebrand
 */
$messages['nl'] = array(
	'timeline-desc' => 'Voegt de tag <code>&lt;timeline&gt;</code> toe om tijdlijnen te maken',
	'timeline-invalidmap' => 'EasyTimeline heeft een ongeldige afbeelding gegenereerd',
);

/** Norwegian Nynorsk (norsk (nynorsk)‎)
 * @author Frokor
 * @author Gunnernett
 */
$messages['nn'] = array(
	'timeline-desc' => 'Legg til taggen <code>&lt;timeline&gt;</code> for å opprette tidslinjer',
	'timeline-invalidmap' => 'Ugyldig biletkart oppretta av EasyTimeline',
);

/** Occitan (occitan)
 * @author Cedric31
 */
$messages['oc'] = array(
	'timeline-desc' => 'Apond la balisa <code>&lt;timeline&gt;</code> per crear de frisas cronologicas',
	'timeline-invalidmap' => "Carta invalida de l'imatge generit per EasyTimeline",
);

/** Oriya (ଓଡ଼ିଆ)
 * @author Psubhashish
 */
$messages['or'] = array(
	'timeline-desc' => 'ସମୟକାଳ ତିଆରି କରିବା ନିମନ୍ତେ <code>&lt;timeline&gt;</code> ଚିହ୍ନ ଯୋଡ଼ିଥାଏ',
	'timeline-invalidmap' => 'EasyTimeline ଦେଇ ତିଆରି ଅଚଳ ଛବି ମାନଚିତ୍ର',
);

/** Deitsch (Deitsch)
 * @author Xqt
 */
$messages['pdc'] = array(
	'timeline-desc' => "Duht's <code>&lt;timeline&gt;</code>-Tag zum Schtaerte vun de Zeitlein dezu",
	'timeline-invalidmap' => "'S Pikder wu EasyTimeline gmacht hot iss letz.",
);

/** Polish (polski)
 * @author Sp5uhe
 */
$messages['pl'] = array(
	'timeline-desc' => 'Dodaje znacznik <code>&lt;timeline&gt;</code> umożliwiający tworzenie spisu na osi czasu',
	'timeline-invalidmap' => 'Nieprawidłowa mapa obrazka wygenerowana przez EasyTimeline',
);

/** Piedmontese (Piemontèis)
 * @author Dragonòt
 */
$messages['pms'] = array(
	'timeline-desc' => 'A gionta ël tag <code>&lt;timeline&gt;</code> për creé dle "timeline"',
	'timeline-invalidmap' => 'Mapa pa bon-a generà da EasyTimeline',
);

/** Western Punjabi (پنجابی)
 * @author Khalid Mahmood
 */
$messages['pnb'] = array(
	'timeline-desc' => 'جوڑو <code>&lt;timeline&gt;</code> ٹیگ ویلہ لیک بنان لئی۔',
	'timeline-invalidmap' => 'ناں منیا جان والا مورت نقشہ ایزیٹائملائن تے بنیا',
);

/** Portuguese (português)
 * @author Giro720
 * @author Hamilton Abreu
 * @author Malafaya
 */
$messages['pt'] = array(
	'timeline-desc' => 'Adiciona o elemento <code>&lt;timeline&gt;</code> para criar linhas temporais',
	'timeline-invalidmap' => 'Image map inválido gerado pelo EasyTimeline',
);

/** Brazilian Portuguese (português do Brasil)
 * @author Daemorris
 * @author Eduardo.mps
 */
$messages['pt-br'] = array(
	'timeline-desc' => 'Adiciona a marca <code>&lt;timeline&gt;</code> para criar linhas de tempo',
	'timeline-invalidmap' => 'O mapa de imagem gerado pelo EasyTimeline é inválido',
);

/** Romanian (română)
 * @author AdiJapan
 */
$messages['ro'] = array(
	'timeline-desc' => 'Adaugă baliza <code>&lt;timeline&gt;</code> pentru a crea grafice temporale.',
	'timeline-invalidmap' => 'Imagine invalidă creată de EasyTimeline',
);

/** tarandíne (tarandíne)
 * @author Joetaras
 */
$messages['roa-tara'] = array(
	'timeline-desc' => "Aggiunge 'u tag <code>&lt;timeline&gt;</code> pe ccreà le linee de timbe",
	'timeline-invalidmap' => "Immaggine d'a mappe invalide generate da EasyTimeline",
);

/** Russian (русский)
 * @author Александр Сигачёв
 */
$messages['ru'] = array(
	'timeline-desc' => 'Добавляет тег <code>&lt;timeline&gt;</code> для создания временных шкал',
	'timeline-invalidmap' => 'Ошибочная карта изображения, созданная EasyTimeline',
);

/** Rusyn (русиньскый)
 * @author Gazeb
 */
$messages['rue'] = array(
	'timeline-desc' => 'Придасть значку <code>&lt;timeline&gt;</code> про створїня часовых шкал',
	'timeline-invalidmap' => 'Неправилна мапа про образок створена EasyTimeline',
);

/** Sanskrit (संस्कृतम्)
 * @author Shubha
 */
$messages['sa'] = array(
	'timeline-desc' => 'कालनिर्देशस्य निर्माणाय <code>&lt;timeline&gt;</code> प्रणाली योज्यते',
	'timeline-invalidmap' => 'ईझिटैम्लैन्-द्वारा निर्मितः निरर्थकः चित्रपटः',
);

/** Sakha (саха тыла)
 * @author HalanTul
 */
$messages['sah'] = array(
	'timeline-desc' => 'Кэм шкалаатын оҥорорго анаан <code>&lt;timeline&gt;</code> тиэги эбэр',
	'timeline-invalidmap' => 'Алҕастаах ойуу каартата, EasyTimeline көмөтүнэн оҥоһуллубут',
);

/** Sicilian (sicilianu)
 * @author Santu
 */
$messages['scn'] = array(
	'timeline-desc' => 'Nzirisci li tag <code>&lt;timeline&gt;</code> pi criari gràfichi timpurali',
);

/** Sinhala (සිංහල)
 * @author Budhajeewa
 */
$messages['si'] = array(
	'timeline-desc' => 'කාලරේඛා තැනුමට <code>&lt;timeline&gt;</code> ටැගය එක් කරයි',
	'timeline-invalidmap' => 'EasyTimeline මගින් සදොස් image map යක් ජනිතය',
);

/** Slovak (slovenčina)
 * @author Helix84
 */
$messages['sk'] = array(
	'timeline-desc' => 'Pridáva značku <code>&lt;timeline&gt;</code> pre tvorbu časových línií',
	'timeline-invalidmap' => 'Neplatná obrazová mapa, ktorú vytvoril EasyTimeline',
);

/** Slovenian (slovenščina)
 * @author Dbc334
 */
$messages['sl'] = array(
	'timeline-desc' => 'Doda etiketo <code>&lt;timeline&gt;</code> za ustvarjanje časovnih potekov',
	'timeline-invalidmap' => 'Neveljavna slika zemljevida generirana z EasyTimeline',
);

/** Albanian (shqip)
 * @author Olsi
 */
$messages['sq'] = array(
	'timeline-desc' => 'Shton etiketën <code>&lt;timeline&gt;</code> për të krijuar afate',
	'timeline-invalidmap' => 'Figurë hartë e pavlefshme e gjeneruar nga EasyTimeline',
);

/** Serbian (Cyrillic script) (српски (ћирилица)‎)
 * @author Millosh
 */
$messages['sr-ec'] = array(
	'timeline-desc' => 'Додаје <code>&lt;timeline&gt;</code> ознаку за стварање временских оса.',
);

/** Serbian (Latin script) (srpski (latinica)‎)
 * @author Michaello
 */
$messages['sr-el'] = array(
	'timeline-desc' => 'Dodaje <code>&lt;timeline&gt;</code> oznaku za stvaranje vremenskih osa.',
);

/** Seeltersk (Seeltersk)
 * @author Pyt
 */
$messages['stq'] = array(
	'timeline-desc' => 'Föiget dät <code>&lt;timeline&gt;</code>-Tag tou dät Moakjen fon Tiedliesten bietou',
);

/** Sundanese (Basa Sunda)
 * @author Kandar
 */
$messages['su'] = array(
	'timeline-desc' => 'Nambahkeun tag <code>&lt;timeline&gt;</code> pikeun nyieun gurat waktu',
	'timeline-invalidmap' => 'Peta gambar nu dihasilkeun ku EasyTimeline teu bener',
);

/** Swedish (svenska)
 * @author Lejonel
 * @author Per
 */
$messages['sv'] = array(
	'timeline-desc' => 'Lägger till taggen <code>&lt;timeline&gt;</code> för att skapa tidslinjer',
	'timeline-invalidmap' => 'EasyTimeline har skapat en ogiltig bildkarta',
);

/** Tamil (தமிழ்)
 * @author Shanmugamp7
 */
$messages['ta'] = array(
	'timeline-desc' => 'காலவரிசைகள் உருவாக்க குறிச்சொல்<code>&lt;timeline&gt;</code>சேர்க்கிறது',
);

/** Telugu (తెలుగు)
 * @author Veeven
 */
$messages['te'] = array(
	'timeline-desc' => 'కాలరేఖలని సృష్టించడానికై <code>&lt;timeline&gt;</code> అనే టాగుని చేరుస్తుంది',
);

/** Tajik (Cyrillic script) (тоҷикӣ)
 * @author Ibrahim
 */
$messages['tg-cyrl'] = array(
	'timeline-desc' => 'Барчасби <code>&lt;timeline&gt;</code>-ро баро намоиши хати замоне илова мекунад',
);

/** Tajik (Latin script) (tojikī)
 * @author Liangent
 */
$messages['tg-latn'] = array(
	'timeline-desc' => 'Barcasbi <code>&lt;timeline&gt;</code>-ro baro namoişi xati zamone ilova mekunad',
);

/** Tagalog (Tagalog)
 * @author AnakngAraw
 */
$messages['tl'] = array(
	'timeline-desc' => "Nagdaragdag ng tatak na <code>&lt;timeline&gt;</code> upang makalikha ng mga pana-panahon (''timeline'')",
	'timeline-invalidmap' => 'Hindi tanggap na mapa ng larawan na nilikha ng EasyTimeline',
);

/** Turkish (Türkçe)
 * @author Joseph
 */
$messages['tr'] = array(
	'timeline-desc' => 'Zaman çizelgesi oluşturmak için <code>&lt;timeline&gt;</code> etiketini ekler',
	'timeline-invalidmap' => 'EasyTimeline tarafından geçersiz resim haritası oluşturuldu',
);

/** Ukrainian (українська)
 * @author AS
 * @author Ahonc
 */
$messages['uk'] = array(
	'timeline-desc' => 'Додає тег <code>&lt;timeline&gt;</code> для створення часових шкал',
	'timeline-invalidmap' => 'Неправильна карта зображення, створена EasyTimeline',
);

/** vèneto (vèneto)
 * @author Candalua
 */
$messages['vec'] = array(
	'timeline-desc' => 'Zonta el tag <code>&lt;timeline&gt;</code> par crear grafici tenporali',
	'timeline-invalidmap' => 'EasyTimeline gà generà na mapa de imagine mia valida',
);

/** Vietnamese (Tiếng Việt)
 * @author Minh Nguyen
 * @author Vinhtantran
 */
$messages['vi'] = array(
	'timeline-desc' => 'Thêm thẻ <code>&lt;timeline&gt;</code> để xây dựng các thời biểu',
	'timeline-invalidmap' => 'EasyTimeline tạo ra bản đồ hình không hợp lệ',
);

/** Yiddish (ייִדיש)
 * @author פוילישער
 */
$messages['yi'] = array(
	'timeline-desc' => 'לייגט צו <code>&lt;timeline&gt;</code> טאַג צו שאפן צײַטליניעס',
	'timeline-invalidmap' => 'אומגילטיקע בילד מאפע גענערירט דורך EasyTimeline',
);

/** Cantonese (粵語)
 * @author Horacewai2
 * @author Shinjiman
 * @author Waihorace
 */
$messages['yue'] = array(
	'timeline-desc' => '加 <code>&lt;timeline&gt;</code> 標籤去建立時間綫',
	'timeline-invalidmap' => '錯誤的圖像地圖 (由EasyTimeline產生)',
);

/** Simplified Chinese (中文（简体）‎)
 * @author Bencmq
 * @author Chenxiaoqino
 * @author Shinjiman
 * @author Xiaomingyan
 */
$messages['zh-hans'] = array(
	'timeline-desc' => '添加<code>&lt;timeline&gt;</code>标签以创建时间轴',
	'timeline-invalidmap' => 'EasyTimeline生成的无效图片地图',
);

/** Traditional Chinese (中文（繁體）‎)
 * @author Gaoxuewei
 * @author Mark85296341
 * @author Shinjiman
 */
$messages['zh-hant'] = array(
	'timeline-desc' => '加入 <code>&lt;timeline&gt;</code> 標籤以建立時間線',
	'timeline-invalidmap' => 'EasyTimeline 產生的無效地圖',
);

/** Chinese (Taiwan) (‪中文(台灣)‬)
 * @author Roc michael
 */
$messages['zh-tw'] = array(
	'timeline-desc' => '新增<code>&lt;timeline&gt;</code> 標記以建立時間線',
);
