<?php
/**
 * Internationalisation file for EasyTimeline extension.
 *
 * @file
 * @ingroup Extensions
 */

$messages = array();

/** English */
$messages['en'] = array(
	'timeline-desc' => 'Adds <code>&lt;timeline&gt;</code> tag to create timelines',
	'timeline-invalidmap' => 'Invalid image map generated by EasyTimeline',
);

/** Message documentation (Message documentation)
 * @author Raimond Spekking
 * @author Raymond
 */
$messages['qqq'] = array(
	'timeline-desc' => 'Extension description displayed on [[Special:Version]]',
);

/** Afrikaans (Afrikaans)
 * @author Naudefj
 */
$messages['af'] = array(
	'timeline-desc' => 'Maak die <code>&lt;timeline&gt;</code> etiket beskikbaar om tydslyne te maak',
);

/** Aragonese (Aragonés)
 * @author Juanpabl
 */
$messages['an'] = array(
	'timeline-desc' => "Adibe a etiqueta <code>&lt;timeline&gt;</code> ta creyar linias d'o tiempo",
);

/** Arabic (العربية)
 * @author Meno25
 */
$messages['ar'] = array(
	'timeline-desc' => 'يضيف الوسم <code>&lt;timeline&gt;</code> لإنشاء الخطوط الزمنية',
	'timeline-invalidmap' => 'صورة خريطة غير صحيحة تم توليدها بواسطة EasyTimeline',
);

/** Egyptian Spoken Arabic (مصرى)
 * @author Ramsis II
 */
$messages['arz'] = array(
	'timeline-desc' => 'بيضيف تاج ال <code>&lt;timeline&gt;</code> علشان ينشيء خطوط الزمن',
);

/** Asturian (Asturianu)
 * @author Esbardu
 */
$messages['ast'] = array(
	'timeline-desc' => 'Añade la etiqueta <code>&lt;timeline&gt;</code> pa crear llinies de tiempu',
);

/** Southern Balochi (بلوچی مکرانی)
 * @author Mostafadaneshvar
 */
$messages['bcc'] = array(
	'timeline-desc' => 'هورکنت <code>&lt;timeline&gt;</code>برچسپء په شرکتن خط زمان',
);

/** Belarusian (Taraškievica orthography) (Беларуская (тарашкевіца))
 * @author Jim-by
 */
$messages['be-tarask'] = array(
	'timeline-desc' => 'Дадае тэг <code>&lt;timeline&gt;</code> для стварэньня часавых шкалаў',
	'timeline-invalidmap' => 'Няслушная выява мапы створаная праз EasyTimeline',
);

/** Bulgarian (Български)
 * @author DCLXVI
 */
$messages['bg'] = array(
	'timeline-desc' => 'Добавя етикета <code>&lt;timeline&gt;</code> за създаване на времеви линии',
);

/** Bengali (বাংলা)
 * @author Abdullah Harun Jewel
 */
$messages['bn'] = array(
	'timeline-desc' => 'সময়সীমা নির্ধারণ
সময়সীমা নির্ধারণ ট্যাগ ব্যবহার করতে যুক্ত করুন: <code>&lt;timeline&gt;</code>',
);

/** Breton (Brezhoneg)
 * @author Fulup
 */
$messages['br'] = array(
	'timeline-desc' => 'Ouzhpennañ a ra ar valizenn <code>&lt;timeline&gt;</code> da grouiñ frizennoù kronologel',
	'timeline-invalidmap' => 'Kartenn direizh ganet dre EasyTimeline',
);

/** Bosnian (Bosanski)
 * @author CERminator
 */
$messages['bs'] = array(
	'timeline-desc' => 'Dodaje oznaku <code>&lt;timeline&gt;</code> za pravljenje vremenskih linija',
	'timeline-invalidmap' => 'Nevaljana mapa slika generisana putem EasyTimeline',
);

/** Catalan (Català)
 * @author Paucabot
 */
$messages['ca'] = array(
	'timeline-desc' => "Afegeix l'etiqueta <code>&lt;timeline&gt;</code> per crear cronologies",
);

/** Czech (Česky)
 * @author Li-sung
 * @author Mormegil
 */
$messages['cs'] = array(
	'timeline-desc' => 'Přidává značku <code>&lt;timeline&gt;</code> na vytváření časových os',
	'timeline-invalidmap' => 'Neplatná mapa k obrázku vytvořená pomocí EasyTimeline',
);

/** German (Deutsch)
 * @author Raimond Spekking
 * @author Umherirrender
 */
$messages['de'] = array(
	'timeline-desc' => 'Fügt das <code>&lt;timeline&gt;</code>-Tag zur Erstellung von Zeitleisten hinzu',
	'timeline-invalidmap' => 'EasyTimeline hat eine ungültige Grafik generiert',
);

/** Zazaki (Zazaki)
 * @author Aspar
 */
$messages['diq'] = array(
	'timeline-desc' => 'qey vıraştışê teqwimi na <code>&lt;timeline&gt;</code> etiket têare keno.',
	'timeline-invalidmap' => 'hetê easyTimeline ra yew xeritaya resmi ya  nemeqbul vıraziya.',
);

/** Lower Sorbian (Dolnoserbski)
 * @author Michawiki
 */
$messages['dsb'] = array(
	'timeline-desc' => 'Pśidawa toflicku <code>&lt;timeline&gt;</code> za napóranje casoweje bałki',
	'timeline-invalidmap' => 'Njepłaśiwa wobrazowa kórta napórana pśez EasyTimeline',
);

/** Greek (Ελληνικά)
 * @author Dead3y3
 * @author Omnipaedista
 */
$messages['el'] = array(
	'timeline-desc' => 'Προσθέτει την ετικέτα <code>&lt;timeline&gt;</code> για την δημιουργία χρονολογιών',
	'timeline-invalidmap' => 'Μή έγκυρος χάρτης εικόνας παρηγμένης από το EasyTimeline',
);

/** Esperanto (Esperanto)
 * @author Yekrats
 */
$messages['eo'] = array(
	'timeline-desc' => 'Aldonas etikedon <code>&lt;timeline&gt;</code> por krei tempoaksojn',
	'timeline-invalidmap' => 'Malvalida bildomapo generita de EasyTimeline',
);

/** Spanish (Español)
 * @author Crazymadlover
 * @author Remember the dot
 */
$messages['es'] = array(
	'timeline-desc' => 'Añade elemento <code>&lt;timeline&gt;</code> para mostrar cronogramas',
	'timeline-invalidmap' => 'Mapa de imagen inválida generada por EasyTimeline',
);

/** Estonian (Eesti)
 * @author Pikne
 */
$messages['et'] = array(
	'timeline-desc' => 'Lisab <code>&lt;timeline&gt;</code>-märgendi ajatelgede loomiseks.',
);

/** Basque (Euskara)
 * @author An13sa
 * @author Theklan
 */
$messages['eu'] = array(
	'timeline-desc' => '<code>&lt;timeline&gt;</code> etiketa gehitzeko du denbora-lerroak sortzeko',
	'timeline-invalidmap' => 'EasyTimeline-k sortutako mapa irudi okerra',
);

/** Persian (فارسی)
 * @author Huji
 */
$messages['fa'] = array(
	'timeline-desc' => 'برچسب <code>&lt;timeline&gt;</code> را برای نمایش خطوط زمانی می‌افزاید',
);

/** Finnish (Suomi)
 * @author Crt
 * @author ZeiP
 */
$messages['fi'] = array(
	'timeline-desc' => 'Lisää <code>&lt;timeline&gt;</code>-tagin aikajanan luomiseksi.',
	'timeline-invalidmap' => 'EasyTimeline loi virheellisen kuvakartan',
);

/** French (Français)
 * @author Crochet.david
 * @author Grondin
 * @author Urhixidur
 */
$messages['fr'] = array(
	'timeline-desc' => 'Ajoute la balise <code>&lt;timeline&gt;</code> pour créer des frises chronologiques',
	'timeline-invalidmap' => 'Carte de l’image générée par EasyTimeline invalide',
);

/** Franco-Provençal (Arpetan)
 * @author ChrisPtDe
 */
$messages['frp'] = array(
	'timeline-desc' => 'Apond la balisa <code>&lt;timeline&gt;</code> por fâre des diagramos cronologicos.',
	'timeline-invalidmap' => 'Mapa envalida de l’émâge fêta per EasyTimeline',
);

/** Friulian (Furlan)
 * @author Klenje
 */
$messages['fur'] = array(
	'timeline-desc' => 'Zonte il tag <code>&lt;timeline&gt;</code> par creâ grafics temporâi',
);

/** Galician (Galego)
 * @author Toliño
 */
$messages['gl'] = array(
	'timeline-desc' => 'Engade a etiqueta <code>&lt;timeline&gt;</code> para crear liñas do tempo',
	'timeline-invalidmap' => 'Mapa inválido da imaxe xerada por EasyTimeline',
);

/** Ancient Greek (Ἀρχαία ἑλληνικὴ)
 * @author Omnipaedista
 */
$messages['grc'] = array(
	'timeline-desc' => 'Προσθέτει τὴν πινακίδα <timeline> καὶ οὕτως ποιεῖ χρονολογίας',
);

/** Swiss German (Alemannisch)
 * @author Als-Holder
 */
$messages['gsw'] = array(
	'timeline-desc' => 'Fiegt s <code>&lt;timeline&gt;</code>-Tag fir s Aalege vu Zytleischte yy',
	'timeline-invalidmap' => 'EasyTimeline het e nit giltigi Abbildig generiert',
);

/** Hebrew (עברית)
 * @author Rotem Liss
 */
$messages['he'] = array(
	'timeline-desc' => 'הוספת תגית <code>&lt;timeline&gt;</code> ליצירת צירי זמן',
	'timeline-invalidmap' => 'נוצרה מפת תמונה בלתי תקינה על ידי EasyTimeline',
);

/** Hindi (हिन्दी)
 * @author Kaustubh
 */
$messages['hi'] = array(
	'timeline-desc' => 'टाईमलाईन तैयार करने के लिये <code>&lt;timeline&gt;</code> टैग देता हैं',
);

/** Hiligaynon (Ilonggo)
 * @author Tagimata
 */
$messages['hil'] = array(
	'timeline-desc' => 'Nagadugang <code>&lt;timeline&gt;</code> tag para mahimo ang mga timeline',
);

/** Croatian (Hrvatski)
 * @author Dalibor Bosits
 * @author Mnalis
 */
$messages['hr'] = array(
	'timeline-desc' => 'Dodaje <code>&lt;timeline&gt;</code> oznaku za stvaranje vremenskih linija',
	'timeline-invalidmap' => 'EasyTimeline je generirao neispravnu slikovnu mapu',
);

/** Upper Sorbian (Hornjoserbsce)
 * @author Michawiki
 */
$messages['hsb'] = array(
	'timeline-desc' => 'Přidawa tafličku <code>&lt;timeline&gt;</code> za wutworjenje časowych lajstow',
	'timeline-invalidmap' => 'Njepłaćiwa wobrazowa karta spłodźena přez EasyTimeline',
);

/** Hungarian (Magyar)
 * @author Dani
 * @author Glanthor Reviol
 */
$messages['hu'] = array(
	'timeline-desc' => 'Idővonal készítése a <code>&lt;timeline&gt;</code> tag segítségével',
	'timeline-invalidmap' => 'Az EasyTimeline érvénytelen image mapet generált',
);

/** Interlingua (Interlingua)
 * @author McDutchie
 */
$messages['ia'] = array(
	'timeline-desc' => 'Adde le etiquetta <code>&lt;timeline&gt;</code> pro crear lineas temporal',
	'timeline-invalidmap' => 'Mappa de imagine invalide generate per EasyTimeline',
);

/** Indonesian (Bahasa Indonesia)
 * @author Bennylin
 * @author IvanLanin
 */
$messages['id'] = array(
	'timeline-desc' => 'Menambahkan tag <code>&lt;timeline&gt;</code> untuk membuat garis waktu',
	'timeline-invalidmap' => 'Peta gambar tidak sah dibuat oleh EasyTimeline',
);

/** Italian (Italiano)
 * @author Beta16
 * @author BrokenArrow
 */
$messages['it'] = array(
	'timeline-desc' => 'Aggiunge il tag <code>&lt;timeline&gt;</code> per creare grafici temporali',
	'timeline-invalidmap' => 'Mappa immagine invalida generata da EasyTimeline',
);

/** Japanese (日本語)
 * @author Fryed-peach
 * @author JtFuruhata
 */
$messages['ja'] = array(
	'timeline-desc' => '年表を作成するための <code>&lt;timeline&gt;</code> タグを追加する',
	'timeline-invalidmap' => 'EasyTimeline によって生成された不正なイメージマップ',
);

/** Jutish (Jysk)
 * @author Huslåke
 */
$messages['jut'] = array(
	'timeline-desc' => 'Tilføje <code>&lt;timeline&gt;</code> tag til kreåsje der tiidlejner',
);

/** Javanese (Basa Jawa)
 * @author Meursault2004
 */
$messages['jv'] = array(
	'timeline-desc' => 'Nambahaké tag <code>&lt;timeline&gt;</code> kanggo nggawé garis wektu',
);

/** Georgian (ქართული)
 * @author გიორგიმელა
 */
$messages['ka'] = array(
	'timeline-desc' => 'ჩაამატეთ თეგი <code>&lt;timeline&gt;</code> დროის სკალის შესაქმნელად',
);

/** Khmer (ភាសាខ្មែរ)
 * @author Lovekhmer
 */
$messages['km'] = array(
	'timeline-desc' => 'ដាក់ប្លាក<code>&lt;timeline&gt;</code>ដើម្បីបង្កើតតារាងពេលវេលា',
);

/** Korean (한국어)
 * @author Kwj2772
 * @author ToePeu
 */
$messages['ko'] = array(
	'timeline-desc' => '시간표를 만들기 위해 <code>&lt;timeline&gt;</code> 태그를 추가합니다.',
	'timeline-invalidmap' => 'EasyTimeline이 잘못된 이미지 맵을 생성하였습니다.',
);

/** Colognian (Ripoarisch)
 * @author Purodha
 */
$messages['ksh'] = array(
	'timeline-desc' => 'Deit dä <code>&lt;timeline&gt;</code>-Befäähl em Wiki dobei, wo mer Belldsche med Linnije med ennem Verlauf fun de Zick met maache kann.',
	'timeline-invalidmap' => '<i lang="en">EasyTimeline</i> hädd_e kapot Diajramm afjelivvert',
);

/** Luxembourgish (Lëtzebuergesch)
 * @author Robby
 */
$messages['lb'] = array(
	'timeline-desc' => 'Setzt den <code>&lt;timeline&gt;</code> Tag derbäi fir Zäitlinnen ze maachen',
	'timeline-invalidmap' => 'EasyTimeLine huet e Bild vun enger Kaart generéiert dat net valabel ass',
);

/** Limburgish (Limburgs)
 * @author Matthias
 */
$messages['li'] = array(
	'timeline-desc' => 'Voegt de tag <code>&lt;timeline&gt;</code> toe om tiedliene te make',
);

/** Lithuanian (Lietuvių)
 * @author Garas
 * @author Vpovilaitis
 */
$messages['lt'] = array(
	'timeline-desc' => 'Sukuria laiko grafikus naudojant gairę <code>&lt;timeline&gt;</code>',
);

/** Macedonian (Македонски)
 * @author Bjankuloski06
 */
$messages['mk'] = array(
	'timeline-desc' => 'Додава ознака <code>&lt;timeline&gt;</code> за да прави хронологии',
	'timeline-invalidmap' => 'Грешна карта за слика доздадена од EasyTimeline',
);

/** Malayalam (മലയാളം)
 * @author Praveenp
 * @author Shijualex
 */
$messages['ml'] = array(
	'timeline-desc' => 'നാൾ വഴി ഉണ്ടാക്കുവാൻ വേണ്ടി <code>&lt;timeline&gt;</code> എന്ന ടാഗ് ചേർക്കുന്നു',
	'timeline-invalidmap' => 'ഈസിറ്റൈംലൈൻ സൃഷ്ടിച്ച അസാധുവായ രേഖാചിത്രം',
);

/** Marathi (मराठी)
 * @author Kaustubh
 */
$messages['mr'] = array(
	'timeline-desc' => 'टाईमलाईन तयार करण्यासाठी <code>&lt;timeline&gt;</code> टॅग वाढवितो',
);

/** Malay (Bahasa Melayu)
 * @author Aviator
 */
$messages['ms'] = array(
	'timeline-desc' => 'Menambah tag <code>&lt;timeline&gt;</code> untuk mencipta garis masa',
);

/** Low German (Plattdüütsch)
 * @author Slomox
 */
$messages['nds'] = array(
	'timeline-desc' => 'Föögt dat <code>&lt;timeline&gt;</code>-Tag för dat Opstellen vun Tietliesten to',
);

/** Dutch (Nederlands)
 * @author Siebrand
 */
$messages['nl'] = array(
	'timeline-desc' => 'Voegt de tag <code>&lt;timeline&gt;</code> toe om tijdlijnen te maken',
	'timeline-invalidmap' => 'EasyTimeline heeft een ongeldige afbeelding gegenereerd',
);

/** Norwegian Nynorsk (‪Norsk (nynorsk)‬)
 * @author Frokor
 * @author Gunnernett
 */
$messages['nn'] = array(
	'timeline-desc' => 'Legg til taggen <code>&lt;timeline&gt;</code> for å opprette tidslinjer',
	'timeline-invalidmap' => 'Ugyldig biletkart oppretta av EasyTimeline',
);

/** Norwegian (bokmål)‬ (‪Norsk (bokmål)‬)
 * @author Jon Harald Søby
 */
$messages['no'] = array(
	'timeline-desc' => 'Legger til taggen <code>&lt;timeline&gt;</code> for å opprette tidslinjer',
	'timeline-invalidmap' => 'Ugyldig bildekart opprettet av EasyTimeline',
);

/** Occitan (Occitan)
 * @author Cedric31
 */
$messages['oc'] = array(
	'timeline-desc' => 'Apond la balisa <code>&lt;timeline&gt;</code> per crear de frisas cronologicas',
	'timeline-invalidmap' => "Carta invalida de l'imatge generit per EasyTimeline",
);

/** Polish (Polski)
 * @author Sp5uhe
 */
$messages['pl'] = array(
	'timeline-desc' => 'Dodaje znacznik <code>&lt;timeline&gt;</code> umożliwiający tworzenie spisu na osi czasu',
	'timeline-invalidmap' => 'Nieprawidłowa mapa obrazka wygenerowana przez EasyTimeline',
);

/** Piedmontese (Piemontèis)
 * @author Dragonòt
 */
$messages['pms'] = array(
	'timeline-desc' => 'A gionta ël tag <code>&lt;timeline&gt;</code> për creé dle "timeline"',
	'timeline-invalidmap' => 'Mapa pa bon-a generà da EasyTimeline',
);

/** Portuguese (Português)
 * @author Giro720
 * @author Hamilton Abreu
 * @author Malafaya
 */
$messages['pt'] = array(
	'timeline-desc' => 'Adiciona o elemento <code>&lt;timeline&gt;</code> para criar linhas temporais',
	'timeline-invalidmap' => 'Image map inválido gerado pelo EasyTimeline',
);

/** Brazilian Portuguese (Português do Brasil)
 * @author Daemorris
 * @author Eduardo.mps
 */
$messages['pt-br'] = array(
	'timeline-desc' => 'Adiciona a marca <code>&lt;timeline&gt;</code> para criar linhas de tempo',
	'timeline-invalidmap' => 'O mapa de imagem gerado pelo EasyTimeline é inválido',
);

/** Tarandíne (Tarandíne)
 * @author Joetaras
 */
$messages['roa-tara'] = array(
	'timeline-desc' => "Aggiunge 'u tag <code>&lt;timeline&gt;</code> pe ccreà le linee de timbe",
	'timeline-invalidmap' => "Immaggine d'a mappe invalide generate da EasyTimeline",
);

/** Russian (Русский)
 * @author Александр Сигачёв
 */
$messages['ru'] = array(
	'timeline-desc' => 'Добавляет тег <code>&lt;timeline&gt;</code> для создания временных шкал',
	'timeline-invalidmap' => 'Ошибочная карта изображения, созданная EasyTimeline',
);

/** Yakut (Саха тыла)
 * @author HalanTul
 */
$messages['sah'] = array(
	'timeline-desc' => 'Кэм шкалаатын оҥорорго анаан <code>&lt;timeline&gt;</code> тиэги эбэр',
	'timeline-invalidmap' => 'Алҕастаах ойуу каартата, EasyTimeline көмөтүнэн оҥоһуллубут',
);

/** Sicilian (Sicilianu)
 * @author Santu
 */
$messages['scn'] = array(
	'timeline-desc' => 'Nzirisci li tag <code>&lt;timeline&gt;</code> pi criari gràfichi timpurali',
);

/** Slovak (Slovenčina)
 * @author Helix84
 */
$messages['sk'] = array(
	'timeline-desc' => 'Pridáva značku <code>&lt;timeline&gt;</code> pre tvorbu časových línií',
	'timeline-invalidmap' => 'Neplatná obrazová mapa, ktorú vytvoril EasyTimeline',
);

/** Slovenian (Slovenščina)
 * @author Dbc334
 */
$messages['sl'] = array(
	'timeline-desc' => 'Doda etiketo <code>&lt;timeline&gt;</code> za ustvarjanje časovnih potekov',
	'timeline-invalidmap' => 'Neveljavna slika zemljevida generirana z EasyTimeline',
);

/** Serbian Cyrillic ekavian (Српски (ћирилица))
 * @author Millosh
 */
$messages['sr-ec'] = array(
	'timeline-desc' => 'Додаје <code>&lt;timeline&gt;</code> ознаку за стварање временских оса.',
);

/** Serbian Latin ekavian (Srpski (latinica))
 * @author Michaello
 */
$messages['sr-el'] = array(
	'timeline-desc' => 'Dodaje <code>&lt;timeline&gt;</code> oznaku za stvaranje vremenskih osa.',
);

/** Seeltersk (Seeltersk)
 * @author Pyt
 */
$messages['stq'] = array(
	'timeline-desc' => 'Föiget dät <code>&lt;timeline&gt;</code>-Tag tou dät Moakjen fon Tiedliesten bietou',
);

/** Sundanese (Basa Sunda)
 * @author Kandar
 */
$messages['su'] = array(
	'timeline-desc' => 'Nambahkeun tag <code>&lt;timeline&gt;</code> pikeun nyieun gurat waktu',
	'timeline-invalidmap' => 'Peta gambar nu dihasilkeun ku EasyTimeline teu bener',
);

/** Swedish (Svenska)
 * @author Lejonel
 * @author Per
 */
$messages['sv'] = array(
	'timeline-desc' => 'Lägger till taggen <code>&lt;timeline&gt;</code> för att skapa tidslinjer',
	'timeline-invalidmap' => 'EasyTimeline har skapat en ogiltig bildkarta',
);

/** Telugu (తెలుగు)
 * @author Veeven
 */
$messages['te'] = array(
	'timeline-desc' => 'కాలరేఖలని సృష్టించడానికై <code>&lt;timeline&gt;</code> అనే టాగుని చేరుస్తుంది',
);

/** Tajik (Cyrillic) (Тоҷикӣ (Cyrillic))
 * @author Ibrahim
 */
$messages['tg-cyrl'] = array(
	'timeline-desc' => 'Барчасби <code>&lt;timeline&gt;</code>-ро баро намоиши хати замоне илова мекунад',
);

/** Tajik (Latin) (Тоҷикӣ (Latin))
 * @author Liangent
 */
$messages['tg-latn'] = array(
	'timeline-desc' => 'Barcasbi <code>&lt;timeline&gt;</code>-ro baro namoişi xati zamone ilova mekunad',
);

/** Tagalog (Tagalog)
 * @author AnakngAraw
 */
$messages['tl'] = array(
	'timeline-desc' => "Nagdaragdag ng tatak na <code>&lt;timeline&gt;</code> upang makalikha ng mga pana-panahon (''timeline'')",
	'timeline-invalidmap' => 'Hindi tanggap na mapa ng larawan na nilikha ng EasyTimeline',
);

/** Turkish (Türkçe)
 * @author Joseph
 */
$messages['tr'] = array(
	'timeline-desc' => 'Zaman çizelgesi oluşturmak için <code>&lt;timeline&gt;</code> etiketini ekler',
	'timeline-invalidmap' => 'EasyTimeline tarafından geçersiz resim haritası oluşturuldu',
);

/** Ukrainian (Українська)
 * @author AS
 * @author Ahonc
 */
$messages['uk'] = array(
	'timeline-desc' => 'Додає тег <code>&lt;timeline&gt;</code> для створення часових шкал',
	'timeline-invalidmap' => 'Неправильна карта зображення, створена EasyTimeline',
);

/** Vèneto (Vèneto)
 * @author Candalua
 */
$messages['vec'] = array(
	'timeline-desc' => 'Zonta el tag <code>&lt;timeline&gt;</code> par crear grafici tenporali',
	'timeline-invalidmap' => 'EasyTimeline gà generà na mapa de imagine mia valida',
);

/** Vietnamese (Tiếng Việt)
 * @author Minh Nguyen
 * @author Vinhtantran
 */
$messages['vi'] = array(
	'timeline-desc' => 'Thêm thẻ <code>&lt;timeline&gt;</code> để xây dựng các thời biểu',
	'timeline-invalidmap' => 'EasyTimeline tạo ra bản đồ hình không hợp lệ',
);

/** Cantonese (粵語)
 * @author Horacewai2
 * @author Shinjiman
 */
$messages['yue'] = array(
	'timeline-desc' => '加 <code>&lt;timeline&gt;</code> 標籤去建立時間綫',
	'timeline-invalidmap' => '錯誤的圖像地圖 (由EasyTimeline產生)',
);

/** Simplified Chinese (‪中文(简体)‬)
 * @author Bencmq
 * @author Shinjiman
 */
$messages['zh-hans'] = array(
	'timeline-desc' => '加入 <code>&lt;timeline&gt;</code> 标签以建立时间线',
	'timeline-invalidmap' => 'EasyTimeline生成的无效图片',
);

/** Traditional Chinese (‪中文(繁體)‬)
 * @author Gaoxuewei
 * @author Shinjiman
 */
$messages['zh-hant'] = array(
	'timeline-desc' => '加入 <code>&lt;timeline&gt;</code> 標籤以建立時間線',
	'timeline-invalidmap' => 'EasyTimeline生成的無效地圖',
);

/** Chinese (Taiwan) (‪中文(台灣)‬)
 * @author Roc michael
 */
$messages['zh-tw'] = array(
	'timeline-desc' => '新增<code>&lt;timeline&gt;</code> 標記以建立時間線',
);

